openapi: 3.0.3
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
  securitySchemes:
    my_authentication:
      type: http
      scheme: bearer
      bearerFormat: http
info:
  title: Auto Deal Payment
  description: API documentation for the Auto Deal Payment service
  version: '1'
security:
  - my_authentication: []
paths:
  /webhook:
    post:
      summary: Webhook notification receiver
      description: Endpoint responsible for receiving webhook response from Mercado Pago
      operationId: notify
      parameters: []
      tags: []
      responses:
        '200':
          description: Notification received
          headers: {}
        '400':
          description: Validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
        '500':
          description: Database errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
  /payment:
    get:
      summary: Get Payment details
      description: Endpoint retrieving payment information from DynamoDB
      operationId: payment
      parameters: []
      tags: []
      responses:
        '200':
          description: Payment response retrieved
          headers: {}
        '404':
          description: idempotency_key not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
        '500':
          description: Database errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
