service: auto-deal-payment
frameworkVersion: '3'
params:
  default:
    audienceIssuerUrl: ${env.AUDIENCE_ISSUER_URL}
    audienceClientId: ${env.AUDIENCE_CLIENT_ID}
    failedPaymentQueueArn: ${env.FAILED_PAYMENT_QUEUE_ARN}
    successPaymentQueueArn: ${env.SUCCESS_PAYMENT_QUEUE_ARN}
custom:
  tableName: 'auto-deal-payment-${sls:stage}'

provider:
  name: aws
  ecr:
    images:
      auto-deal-payment:
        path: ./
        platform: linux/arm64
  stage: dev
  region: us-east-1
  runtime: python3.10
  timeout: 30
  deploymentMethod: direct
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ AutoDealPaymentTable, Arn ]
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - ${param:failedPaymentQueueArn}
            - ${param:successPaymentQueueArn}
  environment:
    TABLE_NAME: ${env.TABLE_NAME}
    ENV_ACCESS_TOKEN: ${env.ENV_ACCESS_TOKEN}
    MERCADO_PAGO_API_URL: ${env.MERCADO_PAGO_API_URL}
    SUCCESS_PAYMENT_QUEUE_URL: ${{ secrets.SUCCESS_PAYMENT_QUEUE_URL }}
    FAILED_PAYMENT_QUEUE_URL: ${{ secrets.FAILED_PAYMENT_QUEUE_URL }}
    ZIP_CODE: ${env.ZIP_CODE}
    STREET_NAME: ${env.STREET_NAME}
    STREET_NUMBER: ${env.STREET_NUMBER}
    NEIGHBORHOOD: ${env.NEIGHBORHOOD}
    CITY: ${env.CITY}
    FEDERAL_UNIT: ${env.FEDERAL_UNIT}
    DEFAULT_EMAIL: ${env.DEFAULT_EMAIL}

  httpApi:
    cors: true
    authorizers:
      autoDealAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${param:audienceIssuerUrl}
        audience:
          - ${param:audienceClientId}
  architecture: arm64
functions:
  pay:
    image:
      name: auto-deal-payment
      command: ["payment.adapters.controllers.pay_controller.create_payment"]
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ InitializePaymentQueue, Arn ]
          batchSize: 10
  webhook-notify:
    image:
      name: auto-deal-payment
      command: ["payment.adapters.controllers.webhook_controller.webhook_notify"]
    events:
      - httpApi:
          path: /webhook
          method: post
  get-payment:
    image:
      name: auto-deal-payment
      command: ["payment.adapters.controllers.get_payment_controller.get_payment"]
    events:
      - httpApi:
          path: /payment
          method: get
          authorizer:
            name: autoDealAuthorizer

plugins:
  - serverless-dotenv-plugin
  - serverless-openapi-documenter

resources:
  Resources:
    AutoDealPaymentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: payment_id
            AttributeType: N
        KeySchema:
          - AttributeName: payment_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
    InitializePaymentQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: initialize-payment-queue
        VisibilityTimeout: 30
        MessageRetentionPeriod: 300
